Mounted at /content/gdrive
17
10



---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-32-84e8748b7fe2> in <module>()
      1 # save_total_grid(data, number = None, energy_res = None, gen_left_values = None, gen_right_values = [ [None, None], [None, None] ], path = None)
----> 2 f_s.save_total_grid(results, number = data_number, energy_res = en, gen_left_values = gen_left_values, gen_right_values = gen_right_values)

NameError: name 'en' is not defined
